name: Navigation2_extensions_CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: 
      - cf-890_ci_navigation2_ectension
      - develop
      - master
      - "release/*"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: 
      image: ros:humble-ros-base

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: src/${{ github.event.repository.name }}

    - name: Clone Dep's
      run: |
        git clone https://github.com/usdot-fhwa-stol/carma-msgs
        git clone -b nav2_route_server_humble https://github.com/usdot-fhwa-stol/navigation2
      working-directory: /__w/navigation2_extensions/navigation2_extensions/src
         
    - name: Install Ros dependencies
      run: |
        sudo apt-get update
        apt install -y libnanoflann-dev
        rosdep update
        rosdep install --from-paths /__w/navigation2_extensions/navigation2_extensions/src --ignore-src --rosdistro=humble -y -r
      working-directory: /__w/navigation2_extensions/navigation2_extensions/src/navigation2_extensions
    - name: Locate and Source setup.bash
      run: |
        SETUP_BASH=$(find /root/c1t_ws -name setup.bash)
        if [[ -f "$SETUP_BASH" ]]; then
          echo "Found setup.bash at $SETUP_BASH"
          source "$SETUP_BASH"
        else
          echo "setup.bash not found."
          exit 1
        fi
      shell: bash         
    # - name: Build 
    #   run: |
    #     . /opt/ros/humble/setup.sh
    #     colcon build --parallel-workers 4 --event-handlers console_direct+ --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="${COVERAGE_FLAGS}" -DCMAKE_C_FLAGS="${COVERAGE_FLAGS}" -DCMAKE_BUILD_TYPE="Debug"
    #   working-directory: /__w/navigation2_extensions/navigation2_extensions/

    - name: Run tests
      run: |
        colcon test --packages-select carma_nav2_port_drayage_demo carma-nav2_behavior_tree
      working-directory: /__w/navigation2_extensions/navigation2_extensions/

    - name: Run SonarScanner
      uses: usdot-fhwa-stol/actions/sonar-scanner@main
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        working-dir: /github/workspace/ros_ws/src/navigation2_extensions  
